üîç [API SCAN]
================================================================================
[!] https://b.ns.hackerone.com/api                               ERROR: HTTPSConnectionPool(host='b.ns.hackerone.com', port=443): Max retries exceeded with url: /api (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://b.ns.hackerone.com/api/v1                            ERROR: HTTPSConnectionPool(host='b.ns.hackerone.com', port=443): Max retries exceeded with url: /api/v1 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://b.ns.hackerone.com/api/v1/users                      ERROR: HTTPSConnectionPool(host='b.ns.hackerone.com', port=443): Max retries exceeded with url: /api/v1/users (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://b.ns.hackerone.com/graphql                           ERROR: HTTPSConnectionPool(host='b.ns.hackerone.com', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://b.ns.hackerone.com/swagger.json                      ERROR: HTTPSConnectionPool(host='b.ns.hackerone.com', port=443): Max retries exceeded with url: /swagger.json (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://b.ns.hackerone.com/openapi.json                      ERROR: HTTPSConnectionPool(host='b.ns.hackerone.com', port=443): Max retries exceeded with url: /openapi.json (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://a.ns.hackerone.com/api                               ERROR: HTTPSConnectionPool(host='a.ns.hackerone.com', port=443): Max retries exceeded with url: /api (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://a.ns.hackerone.com/api/v1                            ERROR: HTTPSConnectionPool(host='a.ns.hackerone.com', port=443): Max retries exceeded with url: /api/v1 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://a.ns.hackerone.com/api/v1/users                      ERROR: HTTPSConnectionPool(host='a.ns.hackerone.com', port=443): Max retries exceeded with url: /api/v1/users (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://a.ns.hackerone.com/graphql                           ERROR: HTTPSConnectionPool(host='a.ns.hackerone.com', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://a.ns.hackerone.com/swagger.json                      ERROR: HTTPSConnectionPool(host='a.ns.hackerone.com', port=443): Max retries exceeded with url: /swagger.json (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://a.ns.hackerone.com/openapi.json                      ERROR: HTTPSConnectionPool(host='a.ns.hackerone.com', port=443): Max retries exceeded with url: /openapi.json (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://resources.hackerone.com/api                          ERROR: HTTPSConnectionPool(host='resources.hackerone.com', port=443): Max retries exceeded with url: /api (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'resources.hackerone.com'. (_ssl.c:1028)")))
[!] https://resources.hackerone.com/api/v1                       ERROR: HTTPSConnectionPool(host='resources.hackerone.com', port=443): Max retries exceeded with url: /api/v1 (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'resources.hackerone.com'. (_ssl.c:1028)")))
[!] https://resources.hackerone.com/api/v1/users                 ERROR: HTTPSConnectionPool(host='resources.hackerone.com', port=443): Max retries exceeded with url: /api/v1/users (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'resources.hackerone.com'. (_ssl.c:1028)")))
[!] https://resources.hackerone.com/graphql                      ERROR: HTTPSConnectionPool(host='resources.hackerone.com', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'resources.hackerone.com'. (_ssl.c:1028)")))
[!] https://resources.hackerone.com/swagger.json                 ERROR: HTTPSConnectionPool(host='resources.hackerone.com', port=443): Max retries exceeded with url: /swagger.json (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'resources.hackerone.com'. (_ssl.c:1028)")))
[!] https://resources.hackerone.com/openapi.json                 ERROR: HTTPSConnectionPool(host='resources.hackerone.com', port=443): Max retries exceeded with url: /openapi.json (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'resources.hackerone.com'. (_ssl.c:1028)")))
[!] https://zendesk2.hackerone.com/api                           ERROR: HTTPSConnectionPool(host='zendesk2.hackerone.com', port=443): Max retries exceeded with url: /api (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk2.hackerone.com/api/v1                        ERROR: HTTPSConnectionPool(host='zendesk2.hackerone.com', port=443): Max retries exceeded with url: /api/v1 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk2.hackerone.com/api/v1/users                  ERROR: HTTPSConnectionPool(host='zendesk2.hackerone.com', port=443): Max retries exceeded with url: /api/v1/users (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk2.hackerone.com/graphql                       ERROR: HTTPSConnectionPool(host='zendesk2.hackerone.com', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk2.hackerone.com/swagger.json                  ERROR: HTTPSConnectionPool(host='zendesk2.hackerone.com', port=443): Max retries exceeded with url: /swagger.json (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk2.hackerone.com/openapi.json                  ERROR: HTTPSConnectionPool(host='zendesk2.hackerone.com', port=443): Max retries exceeded with url: /openapi.json (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk4.hackerone.com/api                           ERROR: HTTPSConnectionPool(host='zendesk4.hackerone.com', port=443): Max retries exceeded with url: /api (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk4.hackerone.com/api/v1                        ERROR: HTTPSConnectionPool(host='zendesk4.hackerone.com', port=443): Max retries exceeded with url: /api/v1 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk4.hackerone.com/api/v1/users                  ERROR: HTTPSConnectionPool(host='zendesk4.hackerone.com', port=443): Max retries exceeded with url: /api/v1/users (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk4.hackerone.com/graphql                       ERROR: HTTPSConnectionPool(host='zendesk4.hackerone.com', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk4.hackerone.com/swagger.json                  ERROR: HTTPSConnectionPool(host='zendesk4.hackerone.com', port=443): Max retries exceeded with url: /swagger.json (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk4.hackerone.com/openapi.json                  ERROR: HTTPSConnectionPool(host='zendesk4.hackerone.com', port=443): Max retries exceeded with url: /openapi.json (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk3.hackerone.com/api                           ERROR: HTTPSConnectionPool(host='zendesk3.hackerone.com', port=443): Max retries exceeded with url: /api (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk3.hackerone.com/api/v1                        ERROR: HTTPSConnectionPool(host='zendesk3.hackerone.com', port=443): Max retries exceeded with url: /api/v1 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk3.hackerone.com/api/v1/users                  ERROR: HTTPSConnectionPool(host='zendesk3.hackerone.com', port=443): Max retries exceeded with url: /api/v1/users (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk3.hackerone.com/graphql                       ERROR: HTTPSConnectionPool(host='zendesk3.hackerone.com', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk3.hackerone.com/swagger.json                  ERROR: HTTPSConnectionPool(host='zendesk3.hackerone.com', port=443): Max retries exceeded with url: /swagger.json (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk3.hackerone.com/openapi.json                  ERROR: HTTPSConnectionPool(host='zendesk3.hackerone.com', port=443): Max retries exceeded with url: /openapi.json (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk1.hackerone.com/api                           ERROR: HTTPSConnectionPool(host='zendesk1.hackerone.com', port=443): Max retries exceeded with url: /api (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk1.hackerone.com/api/v1                        ERROR: HTTPSConnectionPool(host='zendesk1.hackerone.com', port=443): Max retries exceeded with url: /api/v1 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk1.hackerone.com/api/v1/users                  ERROR: HTTPSConnectionPool(host='zendesk1.hackerone.com', port=443): Max retries exceeded with url: /api/v1/users (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk1.hackerone.com/graphql                       ERROR: HTTPSConnectionPool(host='zendesk1.hackerone.com', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk1.hackerone.com/swagger.json                  ERROR: HTTPSConnectionPool(host='zendesk1.hackerone.com', port=443): Max retries exceeded with url: /swagger.json (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[!] https://zendesk1.hackerone.com/openapi.json                  ERROR: HTTPSConnectionPool(host='zendesk1.hackerone.com', port=443): Max retries exceeded with url: /openapi.json (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
[+] https://support.hackerone.com/api/v1                         404  application/json               len=0
[+] https://support.hackerone.com/api/v1/users                   404  application/json               len=0
[+] https://support.hackerone.com/swagger.json                   404  application/json               len=0
================================================================================